server:
  port: 8083

spring:
  application:
    name: trading
  datasource:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: jdbc:postgresql://${PGSERVER}/${PGDATABASE}
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        default_schema: ${PGSCHEMA}
      org:
        hibernate:
          flushMode: COMMIT
    open-in-view: false
  liquibase:
    enabled: true
    liquibase-schema: ${PGSCHEMA}
    password: ${PGPASSWORD}
    user: ${PGUSER}
    default-schema: ${PGSCHEMA}
    change-log: 'classpath:/db/changelog/db.changelog-master.yaml'

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

tinkoff:
  rest:
    basePath: ${TINKOFF_API_HOST}
    token: ${TINKOFF_TOKEN}
    max-total-conn: 100
    default-max-conn-per-route: 20
    conn-request-timeout-millis: 20000
    socket-timeout-millis: 20000
    conn-timeout-millis: 20000

finance-marker:
  basePath: ${FINANCE_MARKER_HOST}
  api-key: ${FINANCE_MARKER_API_KEY}


